### ISSUE TITLE
Add sponsors/affilliated organisations

### ISSUE THREAD

**Issue by SarahMorgan** [STEMGamechangers/STEMGamechangers.github.io#10]
IOP- London and South East Branch, £1000 (Silver)
(Royal Society of Chemistry would be £2000 but still to be confirmed -leave off for now)

Affiliated organisations:
Cavendish Inspiring Women (Cambridge women in physics group)
Imperial College Women in Physics Society

![iop_logo_copy](https://user-images.githubusercontent.com/12696998/42931422-88b1a3ca-8b37-11e8-8f4b-3a9c86876ea4.jpg)
![rounded
![icwip--tojpeg_1434978408329_x2](https://user-images.githubusercontent.com/12696998/42931627-1dd028be-8b38-11e8-949e-de0fd4f34b69.jpg)
_corners](https://user-images.githubusercontent.com/12696998/42931576-f680d92a-8b37-11e8-8855-8bfc9a50774e.jpg)

**Comment by SarahMorgan** [comment]
![icwip--tojpeg_1434978408329_x2](https://user-images.githubusercontent.com/12696998/42931715-50491558-8b38-11e8-8d83-04078ad9ec64.jpg)

**Comment by KirstieJane** [comment]
Awesome - those three are uploaded now.

Below are tasks for me:
- [x] Need to make the images square with same dimensions (otherwise the layout looks odd)

Questions for others:

* Do we want more information next to the logos? I'm not sure how to indicate them as silver etc....I can add a subtitle easily but the layout is a little harder to figure out 😬

**Comment by SarahMorgan** [comment]
@KirstieJane I think for now (esp for getting the website live) it's ok as it is since none of those organisations have specifically signed up to silver etc sponsorship. If/when a company does sign up to a particular level we'll have to find a way of adding that info. I don't think there's any need for any other info though.

**Comment by KirstieJane** [comment]
Done!
